/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import models.Personaje;

/**
 *
 * @author akxlarre
 */
public class JpanelAgregar extends javax.swing.JPanel {

    /**
     * Creates new form JpanelAgregar
     */
    public JpanelAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPlaneta = new javax.swing.JTextField();
        jComboBoxBando = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboxl = new javax.swing.JCheckBox();
        cboxll = new javax.swing.JCheckBox();
        cboxlll = new javax.swing.JCheckBox();
        cboxlV = new javax.swing.JCheckBox();
        cboxV = new javax.swing.JCheckBox();
        cboxVl = new javax.swing.JCheckBox();
        cboxVll = new javax.swing.JCheckBox();
        cboxVlll = new javax.swing.JCheckBox();
        cboxlX = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1190, 920));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(219, 169, 13));
        jLabel3.setText("Nombre");

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setForeground(new java.awt.Color(0, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 255, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(219, 169, 13));
        jLabel2.setText("ID");

        txtID.setBackground(new java.awt.Color(0, 0, 0));
        txtID.setForeground(new java.awt.Color(0, 255, 255));
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 255, 0)));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(219, 169, 13));
        jLabel8.setText("Edad");

        txtEdad.setBackground(new java.awt.Color(0, 0, 0));
        txtEdad.setForeground(new java.awt.Color(0, 255, 255));
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 255, 0)));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(219, 169, 13));
        jLabel5.setText("de origen");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(219, 169, 13));
        jLabel6.setText("Planeta");

        txtPlaneta.setBackground(new java.awt.Color(0, 0, 0));
        txtPlaneta.setForeground(new java.awt.Color(0, 255, 255));
        txtPlaneta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaneta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 255, 0)));
        txtPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlanetaActionPerformed(evt);
            }
        });

        jComboBoxBando.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imperio", "Neutral", "Rebelde" }));
        jComboBoxBando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBandoActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(219, 169, 13));
        jLabel7.setText("Películas");

        cboxl.setForeground(new java.awt.Color(0, 255, 255));
        cboxl.setText("Star Wars: Episodio I - La amenaza fantasma");
        cboxl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxlActionPerformed(evt);
            }
        });

        cboxll.setForeground(new java.awt.Color(0, 255, 255));
        cboxll.setText("Star Wars: Episodio II - El ataque de los clones");

        cboxlll.setForeground(new java.awt.Color(0, 255, 255));
        cboxlll.setText("Star Wars: Episodio III - La venganza de los Sith");

        cboxlV.setForeground(new java.awt.Color(0, 255, 255));
        cboxlV.setText("Star Wars: Episodio IV - Una nueva esperanza");

        cboxV.setForeground(new java.awt.Color(0, 255, 255));
        cboxV.setText("Star Wars: Episodio V - El Imperio contraataca");

        cboxVl.setForeground(new java.awt.Color(0, 255, 255));
        cboxVl.setText("Star Wars: Episode VI - Return of the Jedi");

        cboxVll.setForeground(new java.awt.Color(0, 255, 255));
        cboxVll.setText("Star Wars: Episodio VII - El despertar de la Fuerza");

        cboxVlll.setForeground(new java.awt.Color(0, 255, 255));
        cboxVlll.setText("Star Wars: Episodio VIII - Los últimos Jedi");

        cboxlX.setForeground(new java.awt.Color(0, 255, 255));
        cboxlX.setText("Star Wars: Episodio IX - El ascenso de Skywalker");

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Keraleeyam", 1, 36)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(219, 169, 13));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 169, 13), 5, true));
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Keraleeyam", 1, 36)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(219, 169, 13));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 169, 13), 5, true));
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(219, 169, 13));
        jLabel4.setText("Bando");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxV)
                            .addComponent(cboxlV)
                            .addComponent(cboxVl)
                            .addComponent(cboxVll)
                            .addComponent(cboxVlll)
                            .addComponent(cboxlX)
                            .addComponent(cboxlll)
                            .addComponent(cboxll)
                            .addComponent(cboxl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(559, 559, 559)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(txtPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(579, 579, 579)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(jComboBoxBando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(txtPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(cboxl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxlll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxlV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxVl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxVll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxVlll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxlX)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlanetaActionPerformed

    private void jComboBoxBandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBandoActionPerformed

    private void cboxlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxlActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
        Personaje pj = new Personaje();
        pj.setNombre(txtNombre.getText().toUpperCase());
        try {
        pj.setEdad(Integer.parseInt(txtEdad.getText()));
        } catch (NumberFormatException ex) {
        throw new NumberFormatException("La edad debe ser numérica");
        }
        try {
        pj.setId(Integer.parseInt(txtID.getText()));
        } catch (NumberFormatException ex) {
        throw new NumberFormatException("La Id debe ser numérica");
        
        }
        pj.setPlanetaOrigen(txtPlaneta.getText());
        pj.setBando(jComboBoxBando.getSelectedItem().toString());
        
        ArrayList<String> pelis = new ArrayList();
        for (JCheckBox checkbox : Arrays.asList(cboxl, cboxll, cboxlll, cboxlV, cboxV, cboxVl, cboxVll, cboxVlll, cboxlX)) {
        if (checkbox.isSelected()) {
        pelis.add(checkbox.getText());
        }
        }
        pj.setPeliculas(pelis);
        
        Principal2.db.crearPJ(pj);
        limpiar();
        
        JOptionPane.showMessageDialog(txtNombre, "Se agrego un nuevo personaje");
        //JOptionPane.showMessageDialog(rootPane, "Se agrego un nuevo personaje");
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(txtNombre, ex.getMessage(),"ERROR",0);
        //JOptionPane.showMessageDialog(rootPane, ex.getMessage(),"ERROR",0);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox cboxV;
    private javax.swing.JCheckBox cboxVl;
    private javax.swing.JCheckBox cboxVll;
    private javax.swing.JCheckBox cboxVlll;
    private javax.swing.JCheckBox cboxl;
    private javax.swing.JCheckBox cboxlV;
    private javax.swing.JCheckBox cboxlX;
    private javax.swing.JCheckBox cboxll;
    private javax.swing.JCheckBox cboxlll;
    private javax.swing.JComboBox<String> jComboBoxBando;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaneta;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        txtID.setText("");
        txtNombre.setText("");
        txtPlaneta.setText("");
        txtEdad.setText("");
        cboxl.setSelected(false);
        cboxll.setSelected(false);
        cboxlll.setSelected(false);
        cboxlV.setSelected(false);
        cboxV.setSelected(false);
        cboxVl.setSelected(false);
        cboxVll.setSelected(false);
        cboxVlll.setSelected(false);
        cboxlX.setSelected(false);
    }
}
