/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import models.Personaje;

/**
 *
 * @author akxlarre
 */
public class JpanelListar extends javax.swing.JPanel {

    /**
     * Creates new form JpanelListar
     */
    public JpanelListar() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaListar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jRBtnCualquiera = new javax.swing.JRadioButton();
        jRBtnImperio = new javax.swing.JRadioButton();
        jRBtnNeutral = new javax.swing.JRadioButton();
        jRBtnRebelde = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jComboxPeli = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1190, 920));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 920));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaListar.setBackground(new java.awt.Color(153, 255, 255));
        tablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListar.getTableHeader().setResizingAllowed(false);
        tablaListar.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaListar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 590));

        jLabel2.setForeground(new java.awt.Color(219, 169, 13));
        jLabel2.setText("Filtrar por Pelicula ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, -1, -1));

        jRBtnCualquiera.setForeground(new java.awt.Color(219, 169, 13));
        jRBtnCualquiera.setText("Cualquiera");
        jRBtnCualquiera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnCualquieraActionPerformed(evt);
            }
        });
        jPanel1.add(jRBtnCualquiera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));

        jRBtnImperio.setForeground(new java.awt.Color(219, 169, 13));
        jRBtnImperio.setText("Imperio");
        jPanel1.add(jRBtnImperio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, -1));

        jRBtnNeutral.setForeground(new java.awt.Color(219, 169, 13));
        jRBtnNeutral.setText("Neutral");
        jPanel1.add(jRBtnNeutral, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, -1, -1));

        jRBtnRebelde.setForeground(new java.awt.Color(219, 169, 13));
        jRBtnRebelde.setText("Rebelde");
        jPanel1.add(jRBtnRebelde, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, -1));

        jLabel3.setForeground(new java.awt.Color(219, 169, 13));
        jLabel3.setText("Filtrar por Bando ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, -1));

        jComboxPeli.setForeground(new java.awt.Color(219, 169, 13));
        jComboxPeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Star Wars: Episodio I - La amenaza fantasma", "Star Wars: Episodio II - El ataque de los clones", "Star Wars: Episodio III - La venganza de los Sith", "Star Wars: Episodio IV - Una nueva esperanza", "Star Wars: Episodio V - El Imperio contraataca", "Star Wars: Episode VI - Return of the Jedi", "Star Wars: Episodio VII - El despertar de la Fuerza", "Star Wars: Episodio VIII - Los últimos Jedi", "Star Wars: Episodio IX - El ascenso de Skywalker" }));
        jComboxPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboxPeliActionPerformed(evt);
            }
        });
        jPanel1.add(jComboxPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 340, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Keraleeyam", 1, 36)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(219, 169, 13));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 169, 13), 5, true));
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 630, 150, 70));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Keraleeyam", 1, 36)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(219, 169, 13));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 169, 13), 5, true));
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 190, 70));

        btnFiltrar.setBackground(new java.awt.Color(0, 0, 0));
        btnFiltrar.setFont(new java.awt.Font("Keraleeyam", 1, 36)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(219, 169, 13));
        btnFiltrar.setText("FILTRAR");
        btnFiltrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 169, 13), 5, true));
        btnFiltrar.setContentAreaFilled(false);
        btnFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, 150, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarTabla(){
        String[] encabezado={"NOMBRE","ID", "EDAD","BANDO","PELICULAS"};
        DefaultTableModel modelo=new DefaultTableModel(encabezado, 0);
        String[] datos=new String[5];
        for (Personaje pj : Principal2.db.mostrarPj()) {
            datos[0]=pj.getNombre();
            datos[1]=String.valueOf(pj.getId());
            datos[2]=String.valueOf(pj.getEdad());
            datos[3]=pj.getBando();
        // me falta agregar las peliculas 
            
            modelo.addRow(datos);
        }
        tablaListar.setModel(modelo);
    }
    private void jRBtnCualquieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnCualquieraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtnCualquieraActionPerformed

    private void jComboxPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboxPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboxPeliActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboxPeli;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBtnCualquiera;
    private javax.swing.JRadioButton jRBtnImperio;
    private javax.swing.JRadioButton jRBtnNeutral;
    private javax.swing.JRadioButton jRBtnRebelde;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaListar;
    // End of variables declaration//GEN-END:variables
}
